### ISSUE TITLE
Undefined variable in BaseInteractionValidationBuilder->buildValidation function

### ISSUE THREAD

**Issue by scottrudy** [Learnosity/learnosity-qti#22]
Undefined variable: results in learnosity-qti\src\Processors\QtiV2\In\Validation\BaseInteractionValidationBuilder.php on line 130:

`LogService::log('ResponseProcessing: Unrecognized scoring type: ' . print_r($results, true));`

**Comment by ttton** [comment]
Hi @scottrudy, thanks for raising this. We'll have a fix in for this soon.
